{{- if not .Values.webhook.certManager.enabled }}
{{- $ca := genCA "llm-shield-proxy-ca" 3650 -}}
{{- $cn := printf "%s.%s.svc" (include "llm-shield-proxy.fullname" .) .Release.Namespace -}}
{{- $altName1 := printf "%s.%s.svc.cluster.local" (include "llm-shield-proxy.fullname" .) .Release.Namespace -}}
{{- $cert := genSignedCert $cn nil (list $altName1 $cn) 3650 $ca -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-shield-proxy.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
