#!/usr/bin/env python3
"""Turn a benchmark result posted as an issue into a published row."""

from __future__ import annotations

import argparse
import io
import json
import os
import re
import subprocess  # nosec B404 - git, gh and npm with fixed argument lists
import sys
import tempfile
import unicodedata
import urllib.error
import urllib.request
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
ROWS_FILE = REPO_ROOT / "website" / "src" / "data" / "submitted-rows.json"
WEBSITE = REPO_ROOT / "website"

# Maps issue heading text to field IDs. Must exactly match the headings generated by submit.py.
FIELD_BY_HEADING = {
    "gateway": "gateway",
    "version and configuration": "version",
    "project link": "project_url",
    "ci run link": "run_url",
    "how it reads the stream": "architecture",
    "license": "license",
    "outcome": "outcome",
    "citation block": "citation",
    "notes": "notes",
}

# Required fields. Measurements are excluded to prevent mismatches with the artifact.
REQUIRED_FIELDS = ("gateway", "version", "architecture", "license", "run_url")

# Maps to the `Architecture` union in `website/src/data/results-wall.ts`.
ARCHITECTURES = ("per-chunk", "buffered", "held-tail", "none", "not-stated")

# What an issue form writes into an optional field nobody filled in.
EMPTY_MARKERS = ("_no response_", "_none_", "n/a", "none", "")

RUN_URL = re.compile(
    r"^https://github\.com/([A-Za-z0-9._-]{1,100})/([A-Za-z0-9._-]{1,100})/actions/runs/(\d{1,20})"
)

# Entity ids as a sentence says them. An id that is not here is printed as-is with
# underscores opened out, which reads acceptably for anything the corpus adds later.
ENTITY_WORDS = {
    "EMAIL": "email addresses",
    "SSN": "social security numbers",
    "PHONE": "phone numbers",
    "CREDIT_CARD": "card numbers",
    "AWS_ACCESS_KEY_ID": "AWS keys",
    "GITHUB_TOKEN": "GitHub tokens",  # nosec B105
    "SLACK_TOKEN": "Slack tokens",  # nosec B105
}

MAX_FIELD_CHARS = 200
API_TIMEOUT_SECONDS = 20
# Limits to prevent unzipping excessively large artifacts.
MAX_ARTIFACT_BYTES = 64 * 1024 * 1024
MAX_MEMBER_BYTES = 16 * 1024 * 1024
# Limits to prevent iterating over archives with excessive members.
MAX_MEMBERS = 500
MAX_REPORTS = 25

# Flood guard limit for rows per account.
MAX_ROWS_PER_SUBMITTER = 12


# --------------------------------------------------------------------------- parsing


def parse_submission(body: str) -> dict[str, str]:
    """Split an issue body into fields, by its `### ` headings. Tolerant to reordering."""
    fields: dict[str, str] = {}
    current: Optional[str] = None
    collected: list[str] = []

    def flush() -> None:
        if current is None:
            return
        value = "\n".join(collected).strip()
        fields[current] = "" if value.strip().casefold() in EMPTY_MARKERS else value

    for raw_line in (body or "").replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        heading = re.match(r"^\s{0,3}#{2,4}\s+(.+?)\s*$", raw_line)
        if heading:
            flush()
            current = FIELD_BY_HEADING.get(heading.group(1).strip().casefold())
            collected = []
            continue
        if current is not None:
            collected.append(raw_line)
    flush()
    return fields


def normalize_architecture(value: str) -> Optional[str]:
    """Map a dropdown option to its union value, or None when it is not one of them."""
    text = value.strip().casefold()
    parenthesised = re.search(r"\(([a-z-]+)\)\s*$", text)
    if parenthesised and parenthesised.group(1) in ARCHITECTURES:
        return parenthesised.group(1)
    for option in ARCHITECTURES:
        if text == option or text == option.replace("-", " "):
            return option
    if text in ("not stated", "unknown", ""):
        return "not-stated"
    return None


def clean(value: str, *, limit: int = MAX_FIELD_CHARS) -> str:
    """Make a string safe to publish: remove control characters, replace em dashes, and apply limit."""
    text = unicodedata.normalize("NFC", value or "")
    text = "".join(" " if unicodedata.category(ch) in ("Cc", "Cf", "Zl", "Zp") else ch for ch in text)
    text = text.replace("—", "-")
    text = re.sub(r"\s+", " ", text).strip()
    return text[:limit].strip() if len(text) > limit else text


# ------------------------------------------------------------------- the GitHub API


def _api(url: str) -> Any:
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "llm-shield-proxy-conformance-intake",
            **(
                {"Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}"}
                if os.getenv("GITHUB_TOKEN")
                else {}
            ),
        },
    )
    with urllib.request.urlopen(request, timeout=API_TIMEOUT_SECONDS) as response:  # nosec B310
        return json.loads(response.read().decode("utf-8"))


def _download_zip(owner: str, repo: str, artifact_id: int) -> bytes:
    """Fetch an artifact through `gh` to handle S3 redirects properly without forwarding Authorization headers."""
    # Streamed to disk, not into memory, to avoid large allocations before checking limits.
    with tempfile.NamedTemporaryFile(suffix=".zip", delete=False) as handle:
        destination = Path(handle.name)
    try:
        with destination.open("wb") as sink:
            finished = subprocess.run(  # nosec B603 B607 - fixed argument list, resolved via PATH
                ["gh", "api", f"repos/{owner}/{repo}/actions/artifacts/{artifact_id}/zip"],
                stdout=sink,
                stderr=subprocess.PIPE,
                timeout=180,
                check=False,
            )
        if finished.returncode != 0:
            raise RuntimeError((finished.stderr or b"").decode("utf-8", "replace").strip()[:300])
        if destination.stat().st_size > MAX_ARTIFACT_BYTES:
            raise RuntimeError("artifact is larger than this job will unpack")
        return destination.read_bytes()
    finally:
        destination.unlink(missing_ok=True)


def reports_from_zip(data: bytes) -> dict[str, Any]:
    """Return every JSON report from an artifact zip, bounded by size and member count limits."""
    found: dict[str, Any] = {}
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        # Cap member count to prevent iterating over excessive files.
        for info in archive.infolist()[:MAX_MEMBERS]:
            name = Path(info.filename).name
            if not name.endswith(".json") or info.file_size > MAX_MEMBER_BYTES:
                continue
            try:
                found[name] = json.loads(archive.read(info).decode("utf-8"))
            except (ValueError, UnicodeDecodeError, zipfile.BadZipFile):
                continue
            if len(found) >= MAX_REPORTS:
                break
    return found


def collect_reports(
    owner: str,
    repo: str,
    run_id: str,
    *,
    api: Callable[[str], Any] = _api,
    download: Callable[[str, str, int], bytes] = _download_zip,
) -> tuple[dict[str, Any], str]:
    """Return the JSON reports attached to a run. Ignores errors to yield empty results on failure."""
    try:
        listing = api(f"https://api.github.com/repos/{owner}/{repo}/actions/runs/{run_id}/artifacts")
    except (urllib.error.URLError, OSError, ValueError) as exc:
        return {}, f"The run's artifacts could not be listed ({type(exc).__name__})."
    artifacts = listing.get("artifacts") if isinstance(listing, dict) else None
    if not artifacts:
        return {}, "The run has no artifacts attached, so there was no report to read."

    problems = []
    # The source workflow uploads an operator-only artifact before its combined artifact.
    # Prefer the latter without changing selection for other submitters.
    for artifact in sorted(artifacts, key=lambda item: item.get("name") != "source-reproduction"):
        if artifact.get("expired"):
            problems.append(f"`{artifact.get('name')}` has expired")
            continue
        # Check declared size before fetching.
        declared = artifact.get("size_in_bytes")
        if isinstance(declared, int) and declared > MAX_ARTIFACT_BYTES:
            problems.append(f"`{artifact.get('name')}` is larger than this job will fetch")
            continue
        try:
            reports = reports_from_zip(download(owner, repo, int(artifact["id"])))
        except (RuntimeError, OSError, ValueError, KeyError, zipfile.BadZipFile) as exc:
            problems.append(f"`{artifact.get('name')}` could not be read ({type(exc).__name__})")
            continue
        if any(is_operator_run(report) or is_response_split(report) for report in reports.values()):
            return reports, f"Read from the artifact `{artifact.get('name')}` on that run."
    if problems:
        return {}, "No report could be read: " + "; ".join(problems[:3]) + "."
    return {}, "The run's artifacts contain no benchmark report."


# --------------------------------------------------------------------- provenance


def classify_provenance(
    run_url: str, fetch: Callable[[str], Any] = _api
) -> tuple[str, str, Optional[tuple[str, str, str]]]:
    """Determine provenance value from the linked run, proving branch and repository origin."""
    if not run_url:
        return "submitted-unverified", "No run was linked, so the result is taken at face value.", None
    match = RUN_URL.match(run_url.strip())
    if not match:
        return (
            "submitted-unverified",
            "The run link is not a github.com Actions run URL, so it could not be checked.",
            None,
        )
    owner, repo, run_id = match.groups()
    try:
        run = fetch(f"https://api.github.com/repos/{owner}/{repo}/actions/runs/{run_id}")
    except (urllib.error.URLError, OSError, ValueError) as exc:
        return (
            "submitted-unverified",
            f"The run could not be read ({type(exc).__name__}). A private repository or a "
            "deleted run looks the same from here, so nothing is inferred from it.",
            None,
        )
    if not isinstance(run, dict):
        return "submitted-unverified", "The run API returned something unreadable.", None

    head_repo = run.get("head_repository") or {}
    home_repo = run.get("repository") or {}
    head_name = str(head_repo.get("full_name") or "")
    home_name = str(home_repo.get("full_name") or f"{owner}/{repo}")
    branch = str(run.get("head_branch") or "")
    where = (owner, repo, run_id)

    # Handle missing default_branch in payload.
    default_branch = str(home_repo.get("default_branch") or "")
    if not default_branch:
        try:
            details = fetch(f"https://api.github.com/repos/{owner}/{repo}")
            default_branch = str((details or {}).get("default_branch") or "")
        except (urllib.error.URLError, OSError, ValueError):
            default_branch = ""

    if head_repo.get("fork") or (head_name and head_name != home_name):
        return (
            "submitted-fork",
            f"The run came from the fork `{head_name or 'unknown'}`, so it says what a "
            "change does rather than what the released code does.",
            where,
        )
    if branch and default_branch and branch == default_branch:
        return "submitted-main", f"The run is on `{branch}`, the default branch of `{home_name}`.", where
    if branch:
        return (
            "submitted-branch",
            f"The run is on `{branch}`, which is not the default branch of `{home_name}`, "
            "so it may not be shipping code.",
            where,
        )
    return "submitted-unverified", "The run exists but records no branch.", where


# --------------------------------------------------------- reading the measurements


def is_operator_run(report: Any) -> bool:
    return isinstance(report, dict) and str(report.get("schema", "")).startswith(
        "pii-leak-benchmark/operator-run"
    )


def is_response_split(report: Any) -> bool:
    """A profile that scored the response, whole and split across two chunks."""
    if not isinstance(report, dict):
        return False
    leak = (report.get("metrics") or {}).get("leak_rate")
    return isinstance(leak, dict) and "single_chunk" in leak and "adversarial" in leak


def is_complete_source_pair(on: Any, off: Any) -> bool:
    """Require both response arms to cover the same complete midpoint corpus."""
    if not is_response_split(on) or not is_response_split(off):
        return False
    for arm, report in (("on", on), ("off", off)):
        if report.get("schema") != "llm-shield.streaming-privacy-http-profile/v2.0.0":
            return False
        name = (report.get("implementation") or {}).get("name")
        if not isinstance(name, str) or not name.startswith("external-gateway:") or not name.endswith(f"-response-{arm}"):
            return False
        if ((report.get("checks") or {}).get("configured_upstream_boundary") or {}).get("passed") is not True:
            return False
        metrics = report.get("metrics") or {}
        counts = metrics.get("cases_by_condition") or {}
        if (metrics.get("cases_scored") != 32 or metrics.get("cases_inconclusive") != 0
                or counts.get("single_chunk") != 16 or counts.get("adversarial") != 16
                or (metrics.get("partition_oracle") or {}).get("oracle") != "midpoint"):
            return False
    for field in ("cases_digest", "harness_revision"):
        if not on.get(field) or on[field] != off.get(field):
            return False
    for section, field in (("corpus", "seed"), ("corpus", "sha256"),
                           ("instrument", "inspector_sha256")):
        value = (on.get(section) or {}).get(field)
        if not value or value != (off.get(section) or {}).get(field):
            return False
    return True


def _words(entities: list[str]) -> str:
    said = [ENTITY_WORDS.get(name, name.replace("_", " ").lower()) for name in entities]
    if len(said) == 1:
        return said[0]
    return ", ".join(said[:-1]) + " and " + said[-1]


def derive_measurements(reports: dict[str, Any]) -> dict[str, Any]:
    """Derive columns from the reports. Reads provider reach from operator run, and fidelity from raw report."""
    operator = next((r for r in reports.values() if is_operator_run(r)), None)
    source_on = reports.get("source-response-on.json")
    source_off = reports.get("source-response-off.json")
    if source_on is not None or source_off is not None:
        split = source_on if is_complete_source_pair(source_on, source_off) else None
    else:
        split = next((r for r in reports.values() if is_response_split(r)), None)
    raw = next(
        (
            r
            for name, r in reports.items()
            if isinstance(r, dict) and "checks" in r and not is_operator_run(r) and "raw" in name
        ),
        None,
    )
    derived: dict[str, Any] = {}

    if operator:
        entities = operator.get("entities") or {}
        leaked = sorted(name for name, state in entities.items() if state == "leak")
        measured = sorted(name for name, state in entities.items() if state != "not measured")
        derived["sentN"] = len(leaked)
        if not leaked:
            derived["sent"] = "none"
        elif measured and len(leaked) == len(measured):
            derived["sent"] = f"all {len(measured)} types"
        elif len(leaked) <= 2:
            derived["sent"] = _words(leaked)
        else:
            derived["sent"] = f"{len(leaked)} of {len(measured)} types"
        derived["_leaked"] = leaked
        derived["_measured"] = measured

    fidelity = None
    if raw:
        value = ((raw.get("checks") or {}).get("response_fidelity") or {}).get("passed")
        fidelity = value if isinstance(value, bool) else None
    if fidelity is None and operator:
        value = (operator.get("required_checks") or {}).get("response_fidelity")
        fidelity = value if isinstance(value, bool) else None
    if fidelity is not None:
        derived["restored"] = "all" if fidelity else "none"
        derived["restoredN"] = 1.0 if fidelity else 0.0
    elif split:
        # Enforce exact boolean conditions.
        rate = (split.get("metrics") or {}).get("fidelity_rate")
        if isinstance(rate, (int, float)) and not isinstance(rate, bool) and 0.0 <= rate <= 1.0:
            derived["restored"] = "all" if rate == 1.0 else "none" if rate == 0.0 else "some"
            derived["restoredN"] = float(rate)

    # Each profile may use a different pinned instrument revision.
    operator_harness = ((operator or {}).get("contract") or {}).get("harness_version")
    response_harness = (split or {}).get("harness_revision")
    if operator_harness and response_harness and operator_harness != response_harness:
        derived["harness"] = (
            f"{str(operator_harness)[:16]} (operator), {str(response_harness)[:16]} (response)"
        )
    else:
        for source in (operator, raw, split):
            if not source:
                continue
            value = ((source.get("contract") or {}).get("harness_version")
                     or source.get("harness_revision"))
            if value:
                derived["harness"] = str(value)[:32]
                break

    identity = reports.get("source-identity.json")
    if isinstance(identity, dict) and identity.get("schema") == "pii-leak-benchmark/source-build/v1":
        commit = identity.get("source_commit")
        if isinstance(commit, str) and re.fullmatch(r"[0-9a-f]{40}", commit):
            derived["_source_commit"] = commit

    if split:
        metrics = split.get("metrics") or {}
        leak = metrics.get("leak_rate") or {}
        counts = metrics.get("cases_by_condition") or {}
        for key, condition, text, number in (
            ("single_chunk", "single_chunk", "leakWhole", "leakWholeN"),
            ("adversarial", "adversarial", "leakSplit", "leakSplitN"),
        ):
            rate = leak.get(key)
            total = counts.get(condition)
            if isinstance(rate, (int, float)) and isinstance(total, int) and total > 0:
                derived[text] = f"{round(rate * total)} of {total}"
                derived[number] = float(rate)
    return derived


def write_note(derived: dict[str, Any]) -> str:
    """Build a summary sentence based only on recorded measurements."""
    parts: list[str] = []
    leaked = derived.get("_leaked")
    if leaked is not None:
        parts.append(
            "Kept everything out of the provider request."
            if not leaked
            else f"Sent {_words(leaked)} to the provider."
        )
    restored = derived.get("restored")
    if restored == "all":
        parts.append("Handed every value back to the client.")
    elif restored == "none":
        parts.append("Did not give the caller their own data back.")
    if "leakSplitN" in derived and "leakWholeN" in derived:
        if derived["leakSplitN"] > derived["leakWholeN"]:
            parts.append("Splitting a value across two chunks leaked more of them.")
        elif derived["leakSplitN"] == derived["leakWholeN"]:
            parts.append("Splitting a value changed nothing.")
    if derived.get("_source_commit"):
        parts.append(f"Built from source commit {derived['_source_commit'][:12]}.")
    return " ".join(parts) or "Submitted without a report this check could read."


# ------------------------------------------------------------------------ the row


def validate(fields: dict[str, str]) -> list[str]:
    """Return all validation errors for a submission in a single pass."""
    problems: list[str] = []
    for name in REQUIRED_FIELDS:
        if not fields.get(name, "").strip():
            heading = next(h for h, f in FIELD_BY_HEADING.items() if f == name)
            problems.append(f'The "{heading}" section is empty, and a row cannot be written without it.')
    if fields.get("architecture") and normalize_architecture(fields["architecture"]) is None:
        problems.append(
            'The "how it reads the stream" answer is not one of the offered options: '
            + ", ".join(ARCHITECTURES)
            + "."
        )
    if fields.get("run_url") and not RUN_URL.match(fields["run_url"].strip()):
        problems.append(
            "The run link is not a GitHub Actions run URL. It should look like "
            "`https://github.com/OWNER/REPO/actions/runs/123456789`, and the run has to be "
            "public: the report is read from its artifact rather than from this issue."
        )
    return problems


def build_row(
    fields: dict[str, str],
    provenance: str,
    derived: dict[str, Any],
    *,
    issue_number: int,
    submitter: str,
    date: str,
    evidence: str,
) -> dict[str, Any]:
    """Build the final published or draft row."""
    measured = {key: value for key, value in derived.items() if not key.startswith("_")}
    publishable = "sent" in measured and "restored" in measured
    row: dict[str, Any] = {
        "status": "published" if publishable else "draft",
        "date": date,
        "project": clean(fields.get("gateway", ""), limit=80),
        "version": clean(fields.get("version", ""), limit=120),
        **measured,
        "note": clean(write_note(derived), limit=300),
        "provenance": provenance,
        "architecture": normalize_architecture(fields.get("architecture", "")) or "not-stated",
        "license": clean(fields.get("license", ""), limit=40),
    }
    run_url = clean(fields.get("run_url", ""), limit=300)
    if RUN_URL.match(run_url):
        row["runUrl"] = run_url
    project_url = clean(fields.get("project_url", ""), limit=300)
    if project_url.startswith(("https://", "http://")):
        row["pricingUrl"] = project_url
    # Record the actual repository to defend against misattribution.
    run_match = RUN_URL.match(run_url)
    row["_submission"] = {
        "issue": issue_number,
        "submitter": submitter,
        "ranIn": f"{run_match.group(1)}/{run_match.group(2)}" if run_match else "",
        "evidence": evidence,
        "notes": clean(fields.get("notes", ""), limit=600),
    }
    return row


def render_comment(row: dict[str, Any], reason: str, evidence: str, problems: list[str]) -> str:
    """What the workflow posts back on the issue."""
    if problems:
        lines = ["Thanks for sending this. A few things are missing before it can become a row:", ""]
        lines += [f"- {problem}" for problem in problems]
        lines += ["", "Edit the issue and this check runs again. Nothing is lost."]
        return "\n".join(lines)

    published = row.get("status") == "published"
    body = json.dumps(row, indent=2, ensure_ascii=False)
    lines = [
        "**Published.** Your row is on the [results wall](https://llmshieldproxy.com/docs/conformance/who-has-run-it)."
        if published
        else "**Not published yet.** The submission parsed, but no report could be read from the run.",
        "",
        f"**Who ran it: `{row['provenance']}`.** {reason}",
        "",
        evidence,
        "",
    ]
    if published:
        lines += [
            "Every number in the row was read out of that run's own artifact, not from this "
            "issue. What that establishes is where the run happened and what it recorded, "
            "not that the gateway was the version named: nothing outside your repository "
            "can establish that.",
            "",
        ]
        if "leakWholeN" not in row:
            lines += [
                "The two response-split columns say `not measured`, which is accurate: they "
                "come from a profile that injects values into the response, and the CI check "
                "measures what your gateway sends upstream. Nothing is assumed in their "
                "place.",
                "",
            ]
    else:
        lines += [
            "Link a public Actions run whose artifact holds `current.json` and this check "
            "will fill the row in by itself. Until then the row is parked and nothing about "
            "it is on the page.",
            "",
        ]
    lines += ["<details><summary><b>The row</b></summary>", "", "```json", body, "```", "", "</details>", ""]
    lines += [
        "Anything wrong with it is a bug in this check rather than in your result. Say so "
        "here and it gets fixed."
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- writing


def row_identity(row: dict[str, Any]) -> tuple[str, ...]:
    """Define row identity for deduplication (by run URL if present, otherwise by project/version)."""
    run_url = str(row.get("runUrl") or "")
    if run_url:
        return ("run", run_url)
    return ("target", str(row.get("project", "")).casefold(), str(row.get("version", "")).casefold())


def submissions_by(entries: list[Any], submitter: str) -> int:
    return sum(
        1
        for entry in entries
        if isinstance(entry, dict) and (entry.get("_submission") or {}).get("submitter") == submitter
    )


def append_row(row: dict[str, Any], path: Path = ROWS_FILE) -> None:
    """Safely replace or append to the rows file."""
    document = json.loads(path.read_text(encoding="utf-8"))
    entries = document.setdefault("entries", [])
    if not isinstance(entries, list):
        raise ValueError("submitted-rows.json: 'entries' is not a list")
    identity = row_identity(row)
    document["entries"] = [
        existing
        for existing in entries
        if not (isinstance(existing, dict) and row_identity(existing) == identity)
    ]
    document["entries"].append(row)
    # Write with LF to maintain hash identity.
    path.write_text(
        json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
    )


def _run(*command: str, cwd: Optional[Path] = None) -> None:
    subprocess.run(command, check=True, cwd=cwd or REPO_ROOT)  # nosec B603 - fixed argument lists


def check_row_content() -> None:
    """Run the public-docs style scan before committing to fail fast on banned content."""
    _run("python", "-m", "pytest", "tests/test_public_docs_style.py", "-q")


def build_site() -> None:
    """Run local site build before commit."""
    _run("npm", "ci", "--no-audit", "--no-fund", cwd=WEBSITE)
    _run("npm", "run", "build", cwd=WEBSITE)


def publish(row: dict[str, Any], issue_number: int) -> None:
    """Land the row via an auto-merging pull request."""
    _run("git", "config", "user.name", "github-actions[bot]")
    _run("git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com")
    _run("git", "add", str(ROWS_FILE.relative_to(REPO_ROOT)))

    # Verify only the expected file is staged.
    staged = subprocess.run(  # nosec B603 B607 - fixed argument list
        ["git", "diff", "--cached", "--name-only"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout.split()
    allowed = {ROWS_FILE.relative_to(REPO_ROOT).as_posix()}
    if set(staged) - allowed:
        raise RuntimeError(
            "refusing to publish: this job may only change "
            f"{sorted(allowed)}, and it staged {sorted(staged)}"
        )

    title = f"feat(results-wall): add {row['project']} {row['version']} (#{issue_number})"
    _run("git", "commit", "-m", title)

    # Rebase to prevent unrelated diffs in the PR.
    _run("git", "pull", "--rebase", "origin", "main")
    branch = f"intake/issue-{issue_number}"
    _run("git", "push", "--set-upstream", "origin", f"HEAD:{branch}")

    body = (
        f"Automated from #{issue_number}.\n\n"
        f"Every measured column was read from the artifact of the run linked in that "
        f"issue, not from anything typed in it. Provenance: `{row['provenance']}`.\n\n"
        f"The site was built before this branch was pushed, so the row is known not to "
        f"break it. This pull request may only ever contain "
        f"`{ROWS_FILE.relative_to(REPO_ROOT).as_posix()}`; the job refuses to push if "
        f"anything else is staged.\n\n"
        f"Closes #{issue_number}\n"
    )
    try:
        _run("gh", "pr", "create", "--base", "main", "--head", branch, "--title", title, "--body", body)
        # Auto-merge and squash.
        _run("gh", "pr", "merge", branch, "--auto", "--squash", "--delete-branch")
    except (OSError, subprocess.SubprocessError):
        # Prevent stale branches.
        _try("git", "push", "origin", "--delete", branch)
        raise


def _try(*command: str) -> bool:
    """Run a courtesy action (comment/label/close). Fails gracefully to avoid failing the CI job."""
    finished = subprocess.run(command, cwd=REPO_ROOT, capture_output=True, text=True, check=False)  # nosec B603
    if finished.returncode != 0:
        print(f"Could not {' '.join(command[:3])}: {(finished.stderr or '').strip()[:200]}", file=sys.stderr)
    return finished.returncode == 0


def comment(issue_number: int, text: str) -> bool:
    return _try("gh", "issue", "comment", str(issue_number), "--body", text)


def label(issue_number: int, name: str) -> bool:
    return _try("gh", "issue", "edit", str(issue_number), "--add-label", name)


def close_issue(issue_number: int) -> bool:
    return _try("gh", "issue", "close", str(issue_number), "--reason", "completed")


# ------------------------------------------------------------------------------ main


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--event-path", default=os.getenv("GITHUB_EVENT_PATH"))
    parser.add_argument("--dry-run", action="store_true", help="Print what would happen; touch nothing.")
    args = parser.parse_args(argv)

    if not args.event_path or not Path(args.event_path).is_file():
        print("No event payload to read.", file=sys.stderr)
        return 2
    event = json.loads(Path(args.event_path).read_text(encoding="utf-8"))
    issue = event.get("issue") or {}
    issue_number = int(issue.get("number") or 0)
    if not issue_number:
        print("Event carries no issue number.", file=sys.stderr)
        return 2

    fields = parse_submission(issue.get("body") or "")
    problems = validate(fields)
    row: dict[str, Any] = {}
    reason = evidence = ""
    if not problems:
        provenance, reason, where = classify_provenance(fields.get("run_url", ""))
        reports, evidence = collect_reports(*where) if where else ({}, "No run to read a report from.")
        row = build_row(
            fields,
            provenance,
            derive_measurements(reports),
            issue_number=issue_number,
            submitter=str((issue.get("user") or {}).get("login") or "unknown"),
            # Use issue creation date rather than processing date.
            date=(str(issue.get("created_at") or "")[:10] or datetime.now(timezone.utc).strftime("%Y-%m-%d")),
            evidence=evidence,
        )

    text = render_comment(row, reason, evidence, problems)
    if args.dry_run:
        print(text)
        if row:
            print("\n--- row ---")
            print(json.dumps(row, indent=2, ensure_ascii=False))
        return 1 if problems else 0

    if problems:
        comment(issue_number, text)
        label(issue_number, "needs-info")
        return 1

    # Ensure draft rows are not written to the file.
    if row.get("status") != "published":
        comment(issue_number, text)
        label(issue_number, "needs-info")
        return 1

    # Enforce row limit, allowing replacements.
    existing = json.loads(ROWS_FILE.read_text(encoding="utf-8")).get("entries", [])
    submitter = (row.get("_submission") or {}).get("submitter", "")
    replacing = any(
        isinstance(entry, dict) and row_identity(entry) == row_identity(row) for entry in existing
    )
    if not replacing and submissions_by(existing, submitter) >= MAX_ROWS_PER_SUBMITTER:
        comment(
            issue_number,
            f"This account already holds {MAX_ROWS_PER_SUBMITTER} rows on the wall, which "
            "is the cap, so this one was not published. That is a flood guard rather than "
            "a judgement: if you have a real reason to need more, say so here and it will "
            "be raised. Resubmitting a run that already has a row still works and replaces "
            "it.",
        )
        label(issue_number, "needs-info")
        return 1

    append_row(row)
    # Check row content for style before commit.
    check_row_content()
    # Check site build before commit to prevent broken deploys.
    build_site()
    try:
        publish(row, issue_number)
    except (RuntimeError, OSError, subprocess.SubprocessError) as exc:
        # Notify submitter on failure.
        comment(
            issue_number,
            "This result was read and verified, and then could not be published "
            f"({type(exc).__name__}). Nothing is wrong with your submission and nothing "
            "needs redoing. The failure is on this side and someone will pick it up.",
        )
        label(issue_number, "needs-info")
        print(f"Publishing failed after a successful build: {exc}", file=sys.stderr)
        return 1
    comment(issue_number, text)
    close_issue(issue_number)
    return 0


if __name__ == "__main__":
    sys.exit(main())
