import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'architecture',
    'security',
    'compliance-overview',
    'evidence-plane-status',
    'immutable-retention',
    'deployment',
    'features-overview',
    'glossary',
    'research-publications',
    'policies',
    'guides/mcp-tool-governance',
    'guides/pilot-assessment',
    {
      type: 'category',
      label: 'Open Conformance Lab',
      items: [{type: 'autogenerated', dirName: 'conformance'}],
    },
    {
      type: 'category',
      label: 'Compliance',
      items: [{type: 'autogenerated', dirName: 'compliance'}],
    },
    {
      type: 'category',
      label: 'Features',
      items: [{type: 'autogenerated', dirName: 'features'}],
    },
    {
      type: 'category',
      label: 'Operations & Recipes',
      items: [
        'operations',
        'troubleshooting',
        'litellm-ollama-recipe',
        'openwebui-langchain-recipe',
        'pluggable-rbac-engine',
        'migration-from-presidio',
        'architecture-whitepaper'
      ],
    },
  ],
};

export default sidebars;
