import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * One sidebar per package, matching the four tabs in the navbar.
 *
 * The repository ships four things that are used separately: the proxy, the leak benchmark,
 * the MCP checker and the chunk-invariance test library. Each tab opens its own sidebar, so a
 * visitor who came for one of them never has to read past the other three. Doc URLs did not
 * change when the sidebars were split, so old links still work.
 */
const sidebars: SidebarsConfig = {
  proxySidebar: [
    'proxy',
    'deployment',
    'integrations',
    'features-overview',
    'architecture',
    'security',
    'limitations',
    {
      type: 'category',
      label: 'Features',
      items: [{type: 'autogenerated', dirName: 'features'}],
    },
    {
      type: 'category',
      label: 'Operations & recipes',
      items: [
        'operations',
        'troubleshooting',
        'policies',
        'litellm-ollama-recipe',
        'openwebui-langchain-recipe',
        'pluggable-rbac-engine',
        'migration-from-presidio',
        'guides/mcp-tool-governance',
        'guides/mcp-egress-screening',
      ],
    },
    {
      type: 'category',
      label: 'Compliance & evidence',
      items: [
        'compliance-overview',
        'evidence-plane-status',
        'immutable-retention',
        {type: 'autogenerated', dirName: 'compliance'},
      ],
    },
    {
      type: 'category',
      label: 'More',
      items: [
        'architecture-whitepaper',
        'glossary',
        'research-publications',
        'design-partner-pilot',
        'guides/pilot-assessment',
      ],
    },
  ],
  benchmarkSidebar: [{type: 'autogenerated', dirName: 'conformance'}],
  mcpCheckSidebar: ['mcp-ssrf-check'],
  chunkInvarianceSidebar: ['chunk-invariance', 'split-boundary-leaks'],
};

export default sidebars;
