import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Two top-level sections, and the split is deliberate.
 *
 * The product docs used to sit as sixteen loose entries at the root with the conformance
 * lab as one category among several beneath them. That had two problems. A bare doc id at
 * the root is a plain link, not a collapsible category, so the sixteen were permanently
 * expanded and could not be folded away. And the benchmark read as a subsection of the
 * product rather than as something that measures it, which is the opposite of what it is:
 * `pii-leak-benchmark` ships as its own distribution and is deliberately endpoint-neutral.
 *
 * Both sections are now categories, so both collapse, and the lab stands alongside the
 * product rather than inside it.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'LLM-Shield-Proxy',
      // Open by default: this is the product site, and collapsing it on arrival would
      // hide everything a first visitor came for.
      collapsed: false,
      items: [
        'architecture',
        'security',
        'compliance-overview',
        'evidence-plane-status',
        'immutable-retention',
        'deployment',
        'features-overview',
        'glossary',
        'limitations',
        'research-publications',
        'design-partner-pilot',
        'integrations',
        'policies',
        'guides/mcp-tool-governance',
        'guides/pilot-assessment',
        {
          type: 'category',
          label: 'Compliance',
          items: [{type: 'autogenerated', dirName: 'compliance'}],
        },
        {
          type: 'category',
          label: 'Features',
          items: [{type: 'autogenerated', dirName: 'features'}],
        },
        {
          type: 'category',
          label: 'Operations & Recipes',
          items: [
            'operations',
            'troubleshooting',
            'litellm-ollama-recipe',
            'openwebui-langchain-recipe',
            'pluggable-rbac-engine',
            'migration-from-presidio',
            'architecture-whitepaper',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Open Conformance Lab',
      // Its own top-level section, not a child of the product. The label and landing page
      // come from `docs/conformance/_category_.json`, which is why this carries a `link`:
      // clicking the heading opens the lab's own index rather than merely toggling it.
      link: {type: 'doc', id: 'conformance/index'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'conformance'}],
    },
  ],
};

export default sidebars;
