apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-shield-proxy.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "llm-shield-proxy.name" . }}
    helm.sh/chart: {{ include "llm-shield-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
    VALID_VIRTUAL_KEYS: {{ .Values.config.VALID_VIRTUAL_KEYS | quote }}
