apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-shield-proxy.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "llm-shield-proxy.name" . }}
    helm.sh/chart: {{ include "llm-shield-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  upstream-api-key: {{ .Values.env.UPSTREAM_API_KEY | b64enc | quote }}
  metrics-bearer-token: {{ .Values.env.METRICS_BEARER_TOKEN | b64enc | quote }}
